version: '3.8'

services:
  postgres:
      image: maximstr/post_db
      build:
        context: docker/services/postgres
        dockerfile: Dockerfile
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=kitty
        - POSTGRES_DB=medic
        - POSTGRES_PASSWORD=purrrrrr
      volumes:
        - db-data:/var/lib/postgresql/db-data
      restart: always

  app:
    image: maximstr/java-application
    build:
      context: docker/services/app
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/medic
      - SPRING_DATASOURCE_USERNAME=kitty
      - SPRING_DATASOURCE_PASSWORD=purrrrrr

    depends_on:
      - postgres

volumes:
   db-data: