
create table captains_team
(
    id                        integer generated by default as identity
        primary key,
    username                  varchar
        unique,
    password                  varchar,
    surname                   varchar,
    email                     varchar,
    birthday                  date,
    medic_polys               varchar,
    emergency_phone           varchar,
    place_of_residence        varchar,
    rh_factor                 varchar,
    blood_type                varchar,
    allergy                   varchar,
    medical_contraindications varchar,
    chronic_diseases          varchar,
    metal_implants            varchar,
    electronic_implants       varchar,
    necessary_medicines       varchar,
    role                      varchar,
    create_date               date
);
